# Generated by Django 4.1.3 on 2022-11-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DTWResultGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_index', models.IntegerField()),
                ('graph', models.ImageField(upload_to='')),
            ],
        ),
    ]
